language: node_js
node_js: 
  - "node"
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE palette_picker_test;' -U postgres
  - npm run migrate-test
  - npm run seed-test
notifications:
  email: false

  # add postgres
  # create database
  # migrate/seed DB
  # deploy to heroku